[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38",
    "tqdm >= 4.66.1"
]
build-backend = "setuptools.build_meta"

[project]
name = "techdocs"
<<<<<<< HEAD
version = "0.2.0"
=======
version = "0.2.1"
>>>>>>> 7b80f1bcac446d89a72c4146689db74f434ec4c6
description = "Code documentation generation CLI App"
readme = "README.md"
requires-python = ">=3.10"
authors = [
<<<<<<< HEAD
            {"name" = "test", "email" = "alfatrion123@gmail.com"},
=======
            {"name" = "Caffiene Crew", "email" = "caffienecrewhacks@gmail.com"},
>>>>>>> 7b80f1bcac446d89a72c4146689db74f434ec4c6
]
dependencies = [
    "requests",
]
scripts = {techdocs = "techdocs.cli:main"}


[tool.setuptools]
packages = ["techdocs", "techdocs.utils"]

[tool.setuptools.package-data]
"*" = ["*.json"]